

services:
  backend:
    build: ./apps/backend
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app

  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app

  solver:
    image: python:3.11-slim
    command: tail -f /dev/null

  faissdb:
    image: alpine
    command: tail -f /dev/null




